# Generated by Django 5.2.3 on 2025-07-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='Event',
            new_name='events',
        ),
    ]
