# Generated by Django 5.2.4 on 2025-07-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_asset/default_image.jpg', null=True, upload_to='event_asset'),
        ),
    ]
